#!/usr/bin/env bash
# hyprplace installer.
#
# Three separable concerns, each individually skippable:
#   plugin  Lua modules into the Hyprland config tree
#   config  a require() block in hyprland.lua, delimited by markers
#   bin     a wrapper for the CLI on PATH
#
# Idempotent: re-running converges rather than duplicating. Reversible: `uninstall`
# removes exactly what was added. Learned state is user data and is never removed
# unless --purge is given.
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

MODULES=(init.lua config.lua db.lua identity.lua placement.lua policy.lua learn.lua json.lua cli.lua)

CONFIG_DIR="${HYPRPLACE_CONFIG_DIR:-${XDG_CONFIG_HOME:-$HOME/.config}/hypr}"
BIN_DIR="${HYPRPLACE_BIN_DIR:-$HOME/.local/bin}"
STATE_DIR="${XDG_STATE_HOME:-$HOME/.local/state}/hyprplace"

DO_PLUGIN=1 DO_CONFIG=1 DO_BIN=1 DRY_RUN=0 PURGE=0

BEGIN_MARK="-- >>> hyprplace >>>"
END_MARK="-- <<< hyprplace <<<"

usage() {
    cat <<EOF
usage: install.sh <install|uninstall|status> [options]

  install     copy modules, wire up the config, install the CLI wrapper
  uninstall   undo all three. Learned state is kept unless --purge
  status      report what is installed and whether it matches this checkout

options:
  --dry-run          print what would change, touch nothing
  --no-plugin        skip the Lua modules
  --no-config        skip editing hyprland.lua
  --no-bin           skip the CLI wrapper
  --purge            uninstall only: also delete learned state
  --config-dir DIR   Hyprland config dir (default: $CONFIG_DIR)
  --bin-dir DIR      where the CLI wrapper goes (default: $BIN_DIR)

Editing hyprland.lua is delimited by markers and backed up first. If you would
rather wire it yourself, pass --no-config and add this line:

    require("hyprplace").setup({})
EOF
}

CMD=""
while [ $# -gt 0 ]; do
    case "$1" in
        install|uninstall|status) CMD="$1" ;;
        --dry-run)     DRY_RUN=1 ;;
        --no-plugin)   DO_PLUGIN=0 ;;
        --no-config)   DO_CONFIG=0 ;;
        --no-bin)      DO_BIN=0 ;;
        --purge)       PURGE=1 ;;
        --config-dir)  shift; CONFIG_DIR="$1" ;;
        --bin-dir)     shift; BIN_DIR="$1" ;;
        -h|--help)     usage; exit 0 ;;
        *) echo "unknown argument: $1" >&2; usage >&2; exit 2 ;;
    esac
    shift
done

PLUGIN_DIR="$CONFIG_DIR/hyprplace"
ENTRY="$CONFIG_DIR/hyprland.lua"
WRAPPER="$BIN_DIR/hyprplace"

say()  { printf '  %s\n' "$*"; }
head_() { printf '\n%s\n' "$*"; }
run()  { if [ "$DRY_RUN" = 1 ]; then printf '  would: %s\n' "$*"; else eval "$@"; fi; }

# --------------------------------------------------------------------------- install

install_plugin() {
    head_ "plugin -> $PLUGIN_DIR"
    run "mkdir -p '$PLUGIN_DIR' '$PLUGIN_DIR/bin'"
    local changed=0
    for m in "${MODULES[@]}"; do
        if [ -f "$PLUGIN_DIR/$m" ] && cmp -s "$REPO/$m" "$PLUGIN_DIR/$m"; then
            continue
        fi
        run "cp '$REPO/$m' '$PLUGIN_DIR/$m'"
        changed=$((changed + 1))
    done
    run "cp '$REPO/bin/hyprplace' '$PLUGIN_DIR/bin/hyprplace'"
    run "chmod +x '$PLUGIN_DIR/bin/hyprplace'"
    say "${#MODULES[@]} modules, $changed changed"
}

install_config() {
    head_ "config -> $ENTRY"
    if [ ! -f "$ENTRY" ]; then
        say "NOT FOUND -- create it, or wire hyprplace in yourself:"
        say "    require(\"hyprplace\").setup({})"
        return
    fi

    local block
    block="$BEGIN_MARK
require(\"hyprplace\").setup({})
$END_MARK"

    if grep -qF "$BEGIN_MARK" "$ENTRY"; then
        if [ "$(sed -n "/^${BEGIN_MARK}$/,/^${END_MARK}$/p" "$ENTRY")" = "$block" ]; then
            say "already wired, unchanged"
            return
        fi
        say "updating existing hyprplace block"
        local backup="$ENTRY.hyprplace-backup"
        run "cp '$ENTRY' '$backup'"
        run "awk '/^${BEGIN_MARK}\$/{s=1} !s{print} /^${END_MARK}\$/{s=0}' '$ENTRY' > '$ENTRY.tmp'"
        run "printf '%s\n' \"\$(cat '$ENTRY.tmp')\" > '$ENTRY'"
        run "rm -f '$ENTRY.tmp'"
    else
        say "appending hyprplace block (backup: $ENTRY.hyprplace-backup)"
        run "cp '$ENTRY' '$ENTRY.hyprplace-backup'"
    fi
    run "printf '\n%s\n' \"\$block\" >> '$ENTRY'"
}

install_bin() {
    head_ "bin -> $WRAPPER"
    run "mkdir -p '$BIN_DIR'"
    # A generated wrapper, not a symlink. The CLI locates its modules relative to its
    # own path, and a symlink would resolve to the link's directory -- so the tools
    # would load the repo's modules while the compositor ran the installed ones.
    local tmp="$WRAPPER.tmp"
    if [ "$DRY_RUN" = 1 ]; then
        printf '  would: write wrapper exec-ing %s\n' "$PLUGIN_DIR/bin/hyprplace"
    else
        cat > "$tmp" <<EOF
#!/usr/bin/env bash
# generated by hyprplace install.sh -- do not edit
exec lua "$PLUGIN_DIR/bin/hyprplace" "\$@"
EOF
        chmod +x "$tmp"
        mv "$tmp" "$WRAPPER"
    fi
    case ":$PATH:" in
        *":$BIN_DIR:"*) ;;
        *) say "note: $BIN_DIR is not on your PATH" ;;
    esac
}

# ------------------------------------------------------------------------- uninstall

uninstall_plugin() {
    head_ "plugin"
    if [ ! -d "$PLUGIN_DIR" ]; then say "not installed"; return; fi
    if [ ! -f "$PLUGIN_DIR/init.lua" ]; then
        say "REFUSING: $PLUGIN_DIR does not look like a hyprplace install"
        return
    fi
    run "rm -rf '$PLUGIN_DIR'"
    say "removed $PLUGIN_DIR"
}

uninstall_config() {
    head_ "config"
    if [ ! -f "$ENTRY" ]; then say "$ENTRY not found"; return; fi
    if ! grep -qF "$BEGIN_MARK" "$ENTRY"; then say "no hyprplace block present"; return; fi
    run "cp '$ENTRY' '$ENTRY.hyprplace-backup'"
    run "awk '/^${BEGIN_MARK}\$/{s=1} !s{print} /^${END_MARK}\$/{s=0}' '$ENTRY' > '$ENTRY.tmp' && mv '$ENTRY.tmp' '$ENTRY'"
    say "removed the hyprplace block (backup: $ENTRY.hyprplace-backup)"
}

uninstall_bin() {
    head_ "bin"
    if [ ! -f "$WRAPPER" ]; then say "not installed"; return; fi
    if ! grep -q "generated by hyprplace install.sh" "$WRAPPER"; then
        say "REFUSING: $WRAPPER was not generated by this script"
        return
    fi
    run "rm -f '$WRAPPER'"
    say "removed $WRAPPER"
}

uninstall_state() {
    head_ "state"
    if [ ! -d "$STATE_DIR" ]; then say "none at $STATE_DIR"; return; fi
    if [ "$PURGE" = 1 ]; then
        run "rm -rf '$STATE_DIR'"
        say "purged $STATE_DIR"
    else
        say "kept $STATE_DIR (pass --purge to delete)"
    fi
}

# ---------------------------------------------------------------------------- status

status() {
    head_ "plugin  $PLUGIN_DIR"
    if [ ! -d "$PLUGIN_DIR" ]; then
        say "not installed"
    else
        local stale=0 missing=0
        for m in "${MODULES[@]}"; do
            if [ ! -f "$PLUGIN_DIR/$m" ]; then missing=$((missing + 1))
            elif ! cmp -s "$REPO/$m" "$PLUGIN_DIR/$m"; then stale=$((stale + 1)); fi
        done
        if [ "$missing" = 0 ] && [ "$stale" = 0 ]; then
            say "installed, matches this checkout"
        else
            say "installed, but $stale module(s) differ and $missing missing -- re-run install"
        fi
    fi

    head_ "config  $ENTRY"
    if [ ! -f "$ENTRY" ]; then say "not found"
    elif grep -qF "$BEGIN_MARK" "$ENTRY"; then say "wired"
    else say "not wired"; fi

    head_ "bin     $WRAPPER"
    if [ ! -f "$WRAPPER" ]; then say "not installed"
    elif grep -q "generated by hyprplace install.sh" "$WRAPPER"; then say "installed"
    else say "present, but not generated by this script"; fi

    head_ "state   $STATE_DIR"
    if [ -f "$STATE_DIR/db.lua" ]; then
        say "$(grep -c '] = {' "$STATE_DIR/db.lua" 2>/dev/null || echo 0) entries"
    else
        say "no state yet"
    fi
    printf '\n'
}

case "$CMD" in
    install)
        [ "$DRY_RUN" = 1 ] && echo "DRY RUN -- nothing will be changed"
        [ "$DO_PLUGIN" = 1 ] && install_plugin
        [ "$DO_CONFIG" = 1 ] && install_config
        [ "$DO_BIN" = 1 ] && install_bin
        head_ "done"
        say "reload Hyprland (hyprctl reload) to pick it up"
        printf '\n'
        ;;
    uninstall)
        [ "$DRY_RUN" = 1 ] && echo "DRY RUN -- nothing will be changed"
        [ "$DO_CONFIG" = 1 ] && uninstall_config
        [ "$DO_PLUGIN" = 1 ] && uninstall_plugin
        [ "$DO_BIN" = 1 ] && uninstall_bin
        uninstall_state
        printf '\n'
        ;;
    status) status ;;
    *) usage >&2; exit 2 ;;
esac
